// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Auth struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type Music struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type User struct {
	Email string `json:"email"`
}

type UserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
